on: 
  release:
    types: 
      - created
name: Build Release
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: ngs/go-release.action@v1.0.2
      env:
        # CGO_ENABLED=0 is added so we don't have problems witj ELF
        # Reference: https://github.com/apex/up/issues/734
        CGO_ENABLED: 0
        GOARCH: amd64
        GOOS: linux
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXTRA_FILES: "LICENSE"
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: ngs/go-release.action@v1.0.2
      env:
        CGO_ENABLED: 0
        GOARCH: amd64
        GOOS: darwin
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXTRA_FILES: "LICENSE"
  